%Your Implementation of Newton's method
%INPUTS:
%fun: the mathematical function for which we want to compute the root
%   note that the output of fun may include the derivative
%   i.e. [fval,dfdx] = fun(x)
%   or not, i.e. fval = fun(x)
%x_guess the initial guess for Newton's method
%solver_params: a MATLAB struct containing solver settings
%   solver_params.dxmin: terminate early if |x_{i+1}-x_{i}|<dxmin
%   solver_params.ftol: terminate early if |f(x_i)|<ftol
%   solver_params.max_iter: maximum number of iterations allowed
%   solver_params.dxmax: terminate early if |x_{i+1}-x_{i}|>dxmax
%       (meaning that jacobian is probably singular, which is bad)
%   solver_params.numerical_diff: boolean (0 or 1)
%           1-> numerically differentiate, 0-> use analytical derivative
%should use numerical differentation to compute the Jacobian or
%use a Jacobian generated by fun. No input assumes numerical by default
%   true->fun only needs to return fval
%   false->fun is assumed to return [fval,J]
%OUTPUTS:
%x: the estimate of the root computed by the function
% exit_flag: an integer indicating whether or not the solver succeeded
%   1->small function value, 2->small step, 0->maximum iterations
%   -1->singular Jacobian, -2->invalid or excessive step
function [x, exit_flag] = multi_newton_solver(fun,x_guess,solver_params)
    if nargin<3
        solver_params = struct();
    end

    %unpack values from struct (if fields in struct have been set)
    dxmin = 1e-14;
    if isfield(solver_params,'dxmin')
        dxmin = solver_params.dxmin;
    end

    ftol = 1e-14;
    if isfield(solver_params,'ftol')
        ftol = solver_params.ftol;
    end

    max_iter = 200;
    if isfield(solver_params,'max_iter')
        max_iter = solver_params.max_iter;
    end

    dxmax = 1e8;
    if isfield(solver_params,'dxmax')
        dxmax = solver_params.dxmax;
    end

    numerical_diff = 1;
    if isfield(solver_params,'numerical_diff')
        numerical_diff = solver_params.numerical_diff;
    end

    %initialize the root estimate and exit flag
    x = x_guess;
    exit_flag = 0;

    %iterate Newton's method
    for n = 1:max_iter
        if numerical_diff
            fval = fun(x);
        else
            [fval,J] = fun(x);
        end

        %terminate if the function value is sufficiently small
        if norm(fval)<ftol
            exit_flag = 1;
            return;
        end

        if numerical_diff
            J = approximate_jacobian(fun,x);
        end

        %check for a singular or nearly singular Jacobian
        if any(~isfinite(J(:))) || rcond(J*J')<1e-14
            exit_flag = -1;
            return;
        end

        %compute the Newton step using matrix division
        dx = -(J\fval);

        %terminate if the step is invalid or too large
        if any(~isfinite(dx)) || norm(dx)>dxmax
            exit_flag = -2;
            return;
        end

        x = x+dx;

        %terminate if the step is sufficiently small
        if norm(dx)<dxmin
            exit_flag = 2;
            return;
        end
    end

    %check the final update before reporting maximum iterations
    if norm(fun(x))<ftol
        exit_flag = 1;
    end
end